pipeline {
         agent {
        docker {
            image 'maven:3.6.3'
            args '-v /root/.m2:/root/.m2'
        }
    }
       stages {
        stage('Build') { 
            steps {
                echo 'Executing Maven Build'
                           sh 'mvn -f /var/jenkins_home/workspace/jassmaventest/jenkins/pom.xml -B -DskipTests clean package'
            }
        }
    }
}
