pipeline {
       agent any
       stages {
        stage('Build') { 
            steps {
                echo 'Hello All'
                echo env.WORKSPACE
                dir ('/var/jenkins_home/workspace/jassmaventest/CICD')
                   {
                          echo pwd
                   }
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}
